In [1]:
import numpy as np

In [2]:
x=[1,2,3,4,9,7,8]
arr=np.array(x)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 9, 7, 8])

In [11]:
arr.shape

(7,)

In [18]:
## multinested array

arr1=[1,2,3]
arr2=[4,5,6]
arr3=[7,8,9]
arr4=[10,11,12]

arrr=np.array([arr1,arr2,arr3,arr4])
arrr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
arrr.shape

(4, 3)

In [24]:
arrr.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

## indexing

In [32]:
# accessing the array elements
arra=([1,2,3,4,5,6,7,8,9])
arra

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
arraa=np.array(arra)

In [39]:
arraa

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arraa[5]

6

In [43]:
arraa.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arraa.shape

(9,)

In [49]:
arrr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arrr[:,:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arrr[0:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arrr[0:3,0:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arrr[1:2,1:2]

array([[5]])

In [56]:
## range
ar=np.arange(0,10)
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x=np.arange(1,20,step=2)
x

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [65]:
np.linspace(1,5,12)

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [80]:
## copy() function and broadcasting

x[8:]=10
x

array([  1,   3,   5,   7, 100, 100, 100, 100,  10,  10])

In [82]:
you=np.arange(0,20)
you

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [83]:
you[10:]=50
you

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 50, 50, 50, 50, 50, 50, 50,
       50, 50, 50])

In [84]:
you[:5]=1111
you

array([1111, 1111, 1111, 1111, 1111,    5,    6,    7,    8,    9,   50,
         50,   50,   50,   50,   50,   50,   50,   50,   50])

In [89]:
## some condition very useful in EDA
you<8

array([False, False, False, False, False,  True,  True,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [90]:
you[you<8]

array([5, 6, 7])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [96]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [98]:
np.random.rand(5,3)

array([[0.91189857, 0.95165917, 0.61793388],
       [0.55228004, 0.34022141, 0.40358353],
       [0.72110538, 0.77547568, 0.27891736],
       [0.25419989, 0.9681023 , 0.84468042],
       [0.88213477, 0.3483169 , 0.98196079]])

In [99]:
np.random.randn(5,5)

array([[ 0.80734998, -1.50890303, -0.39332414, -1.68825645,  0.267703  ],
       [ 0.65542509, -0.04080575, -0.20920467,  0.67461361,  0.04439544],
       [ 0.4264038 , -0.28591038, -1.17657462,  2.14582942,  1.63079241],
       [ 1.10702133,  1.06375009, -0.38789349, -0.95674678, -0.08855916],
       [ 0.3228227 , -2.27714577, -0.8449137 ,  0.25320837,  1.82435662]])