In [1]:
import numpy as np

In [4]:
a = np.array([1,2,5,4])
print(a)
print(type(a))

[1 2 5 4]
<class 'numpy.ndarray'>


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# d type
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [10]:
# np.arange
np.arange(1,11,2)



array([1, 3, 5, 7, 9])

In [15]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.random.random((3,4))

array([[0.64320946, 0.47475074, 0.40940793, 0.6375768 ],
       [0.65032269, 0.68710162, 0.90299177, 0.78899112],
       [0.66277761, 0.0824014 , 0.1122871 , 0.8578584 ]])

In [23]:
#np.linspace
np.linspace(-10,5,5)

array([-10.  ,  -6.25,  -2.5 ,   1.25,   5.  ])

In [24]:
# np.identity
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# NUMPY attributes

In [26]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [27]:
print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [28]:
# ndim
a1.ndim

1