In [1]:
import numpy as np

In [4]:
a = np.array([1,2,5,4])
print(a)
print(type(a))

[1 2 5 4]
<class 'numpy.ndarray'>


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# d type
np.array([1,2,3],dtype=bool)

array([ True,  True,  True])

In [10]:
# np.arange
np.arange(1,11,2)



array([1, 3, 5, 7, 9])

In [15]:
# with reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [16]:
# np.ones and np.zeros
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])